apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  application.yml: |-
    spring:
      application:
        name: device-service
      datasource:
        url: jdbc:postgresql://{{ .Values.db.host }}:{{ .Values.db.port }}/{{ .Values.db.name }}
        driver-class-name: org.postgresql.Driver
      # Reste du fichier inchangé