apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  application.yml: |-
    spring:
      application:
        name: device-service
      datasource:
        url: jdbc:postgresql://{{ .Values.env | find "name" "DB_HOST" | pluck "value" | first }}:{{ .Values.env | find "name" "DB_PORT" | pluck "value" | first }}/{{ .Values.env | find "name" "DB_NAME" | pluck "value" | first }}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: {{ eq .Values.environment "dev" }}
        properties:
          hibernate:
            format_sql: {{ eq .Values.environment "dev" }}
            dialect: org.hibernate.dialect.PostgreSQLDialect

    server:
      port: 8080

    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
        prometheus:
          enabled: true
      metrics:
        export:
          prometheus:
            enabled: true

    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method