{{- if .Values.vault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.serviceAccount }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  annotations:
    vault.hashicorp.com/agent-inject: "true"
{{- end }}