{{- if (default false .Values.vault.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-sa" .Release.Name) .Values.vault.serviceAccount }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  annotations:
    vault.hashicorp.com/agent-inject: "true"
{{- end }}