# Valeurs pour l'environnement de développement
environment: dev

image:
  repository: registry.gitlab.com/telecom-net-manager/device-service
  tag: latest
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: device-service-dev.telecom.local
      paths:
        - path: /
          pathType: Prefix

env:
  - name: SPRING_PROFILES_ACTIVE
    value: dev
  - name: DB_HOST
    value: postgres
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: devicedb

# Configuration pour les secrets Vault
vault:
  enabled: true
  secretPath: kubernetes/data/device-service
  role: device-service
  serviceAccount: device-service

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10