# Valeurs pour l'environnement de production
environment: prod

image:
  repository: registry.gitlab.com/telecom-net-manager/device-service
  tag: 1.0.0
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: device-service.telecom.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: device-service-tls
      hosts:
        - device-service.telecom.local

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: DB_HOST
    value: postgres-prod
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: devicedb_prod

# Configuration pour les secrets Vault
vault:
  enabled: true
  secretPath: kubernetes/data/device-service
  role: device-service
  serviceAccount: device-service

# Configuration avancée pour la production
podDisruptionBudget:
  enabled: true
  minAvailable: 2

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  nodegroup: application

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - device-service
          topologyKey: kubernetes.io/hostname

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 90
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 15